Add a legend and vary color by copy number
graph-genome/Schematize pull request #90
Opened 2020-05-22 20:13 UTC by urbanslug

Increase the darkness of the shade with increasing copy number
Fix resetting of color between increased copy number and inverted cells.
Add a color array to mobx store

![output](https://user-images.githubusercontent.com/4144645/82706161-b6371980-9c81-11ea-832a-a0963a506524.gif)

2020-05-22 22:38 UTC, josiahseaman commented
That's a seriously cool gif.  Feedback: The legend needs a second row which is the red color for inversion under increasing copy numbers.  We had talked about combining copy and inversion coloring rules.  This makes it more explicit: two color palettes, one neutral gray for + strand and one red tinted for - strand.  

This is great progress!  Keep up the good work.

P.S. How did you make that smooth gif?

2020-05-22 22:41 UTC, josiahseaman requested changes
What you have is a great improvement.  Let's do one more color palette and then we'll be able to get this to master before our public release.

2020-05-22 22:41 UTC, josiahseaman commented on src/ComponentConnectorRect.js
> +      }
Your code looks really clean!  This is the point where you'd access a second palette array for invesion red colors.

2020-05-22 23:38 UTC, urbanslug commented
What do you think about the legend blocking the matrix?

> The legend needs a second row which is the red color for inversion under increasing copy numbers. We had talked about combining copy and inversion coloring rules. 

What's the color would be best for cells which have increased copy number **and**  are inverted? Also do you mean a second **coloumn**?

What do you think about this?
![image](https://user-images.githubusercontent.com/4144645/82715937-da085880-9c9d-11ea-97ee-efe0581f23ff.png)
or 
![image](https://user-images.githubusercontent.com/4144645/82715997-18057c80-9c9e-11ea-9597-5b1ff62668ac.png)

---

For the gif: 
There are probably easier ways to do it though like firefox add ons but I couldn't find one fast enough so I used quicktime to record the screen into a video (.mov) file then converted it to a gif using ffmpeg. 
I got the instructions for generating the gif here [superuser: How can I get ffmpeg to convert a .mov to a .gif?](https://superuser.com/a/436109).
 - I skipped the convert because it was small
 - I set resolution 1366x768 to have a visible gif

2020-05-23 16:31 UTC, urbanslug commented
Something like this?

![image](https://user-images.githubusercontent.com/4144645/82735665-efc45f00-9d2b-11ea-8a32-571364444d94.png)

2020-05-25 21:39 UTC, josiahseaman commented
Hi Njagi, This is a terrific improvement.  I like the two spectrums, especially the one going to black because it preserves a consistent meaning for darkening color = higher copy number.  I think the legend could be compacted much more, so that the color boxes take up the majority of the space.  Perhaps vertical text would help?  I also find color matching Text in a legend makes things clear.  You could make the actual text of "Inverted" red and allow it to overlap with the other column space.  The color connects these ideas in our mind.  You could also put "Inverted" at the bottom or along the side to indicate it's not competing, but complementing the idea of "Copy Number".

2020-06-02 18:00 UTC, merged